<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Administrator" failures="0" tests="8" name="testDAO.ThongKeDAOTest" time="2.424" errors="2" timestamp="2020-06-30T14:54:19 GMT+07:00" skipped="0">
  <testcase classname="testDAO.ThongKeDAOTest" name="getDiemTheoChuyenDeWithMultipleDataTest" time="0.027"/>
  <system-out/>
  <testcase classname="testDAO.ThongKeDAOTest" name="getDoanhThuTest" time="0.113"/>
  <system-out/>
  <testcase classname="testDAO.ThongKeDAOTest" name="getBangDiemTest" time="0.022">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.polypro.dao.ThongKeDAO.getBangDiem(ThongKeDAO.java:67)
at testDAO.ThongKeDAOTest.getBangDiemTest(ThongKeDAOTest.java:70)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- getBangDiemTest -->
  <system-out/>
  <testcase classname="testDAO.ThongKeDAOTest" name="getNguoiHocWithMultipleDataTest" time="0.021"/>
  <system-out/>
  <testcase classname="testDAO.ThongKeDAOTest" name="getNguoiHocTest" time="2.126"/>
  <system-out/>
  <testcase classname="testDAO.ThongKeDAOTest" name="getBangDiemMultipleDataTest" time="0.040">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.polypro.dao.ThongKeDAO.getBangDiem(ThongKeDAO.java:67)
at testDAO.ThongKeDAOTest.getBangDiemMultipleDataTest(ThongKeDAOTest.java:89)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- getBangDiemMultipleDataTest -->
  <system-out/>
  <testcase classname="testDAO.ThongKeDAOTest" name="getDiemTheoChuyenDeTest" time="0.032"/>
  <system-out/>
  <testcase classname="testDAO.ThongKeDAOTest" name="getDoanhThuWithMultipleDataTest" time="0.043"/>
  <system-out/>
</testsuite> <!-- testDAO.ThongKeDAOTest -->
